### ISSUE TITLE
2 Page views upon landing/refresh

### ISSUE THREAD

**Issue by begonaalvarezd** [imbolc/sapper-google-analytics#1]
Hi, first of all thank you very much for this code, very helpful :pray: 

I have realized that somehow google analytics fires a page view when you land on a website (or refresh) **and** also this package fires one, hence there are 2 page views registered when there should be only one. This issue confuses the bounce rate quite substantially. 

Any idea how to prevent this double trigger?
Thanks :)

**Comment by begonaalvarezd** [comment]
Looks like the param `'send_page_view': false` could fix this issue, to prevent the snippet from sending a pageview hit to Google Analytics. It would look like:

`window.gtag("config", id, { 'send_page_view': false })`

Source: https://developers.google.com/analytics/devguides/collection/gtagjs#disable_pageview_measurement

**Comment by imbolc** [comment]
Hey :) Yep, it seems so, would you send a PR?

**Comment by begonaalvarezd** [comment]
Sure, opened #2

**Comment by imbolc** [comment]
:pray: published
